bundles: auto      
report:                                                 
  pullRequest:  "onAllFiles"
notifications:      
  slack:        
    enabled: false      
useGitClone: false           

